CREATE TABLE `test_user` (
  `LIST_ID` bigint(20) NOT NULL,
  `USER_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `VERSION` bigint(20) DEFAULT NULL,
  `INSERT_BY` bigint(20) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` bigint(20) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `address_id` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;