
CREATE TABLE `test_account` (
  `ACCOUNT_ID` bigint(20) NOT NULL,
  `ACCOUNT_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `INSERT_BY` bigint(20) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_BY` bigint(20) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `IS_DELETE` varchar(100) COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;